import { useRef, useState, type ReactNode } from "react";
import { buildContentMarkdown, normalizeYouTubeId, publicationChecks } from "../lib/cmsMarkdown";
import { publishDocument, setPublicationDate } from "../lib/publication";
import { mediaUrl } from "../lib/mediaRegistry";
import type { ContentDocument, ProjectStatus } from "../types/content";
import type { MediaAsset, MediaRegistry } from "../types/media";
import { TagInput } from "./TagInput";
import { MediaLibrary } from "./MediaLibrary";
import { type EditorImage, VisualEditor } from "./VisualEditor";

type Props = { documents?: ContentDocument[]; document: ContentDocument; statusControl: ReactNode; feedback: ReactNode; disabled: boolean; deployButton: ReactNode; journalDefaultsControl?: ReactNode; registry: MediaRegistry; onChange: (doc: ContentDocument) => void; onSave: () => void; onPublish: () => void; onUnpublish: () => void; onBack: () => void; onDelete: () => void };
export function CmsEditor({ documents = [], document: doc, statusControl, feedback, disabled, deployButton, journalDefaultsControl, registry, onChange, onSave, onPublish, onUnpublish, onBack, onDelete }: Props) {
  const [settings, setSettings] = useState(false); const [media, setMedia] = useState<"body" | "field" | null>(null); const [mediaTarget, setMediaTarget] = useState<string>(""); const [developer, setDeveloper] = useState(false);
  const insertEditorImage = useRef<((image: EditorImage) => void) | null>(null);
  const updateCommon = <K extends keyof ContentDocument["common"]>(key: K, value: ContentDocument["common"][K]) => onChange({ ...doc, common: { ...doc.common, [key]: value } });
  const updatePlacement = (data: ContentDocument["placement"]["data"]) => onChange({ ...doc, placement: { ...doc.placement, data } as ContentDocument["placement"] });
  function chooseMedia(asset: MediaAsset) {
    if (media === "body" && asset.type === "image" && insertEditorImage.current) insertEditorImage.current({ src: mediaUrl(asset.publicId, asset.type), alt: asset.alt || asset.displayName });
    else if (media === "body") { const insertion = asset.type === "video" ? `\n\n<video controls src="${mediaUrl(asset.publicId, asset.type)}"></video>\n\n` : `\n\n<audio controls src="${mediaUrl(asset.publicId, asset.type)}"></audio>\n\n`; onChange({ ...doc, body: `${doc.body.trimEnd()}${insertion}` }); }
    else if (doc.placement.kind === "journal") updatePlacement({ ...doc.placement.data, [mediaTarget]: asset.publicId });
    else if (doc.placement.kind === "gallery") updatePlacement({ ...doc.placement.data, [mediaTarget]: asset.publicId });
    else if (doc.placement.kind === "projects") updatePlacement({ ...doc.placement.data, [mediaTarget]: asset.publicId });
    setMedia(null);
  }
  const checks = publicationChecks(doc.common.publication === "draft" ? publishDocument(doc) : doc); const canPublish = checks.every((check) => check.ok);
  return <main className="editor-shell"><header className="editor-topbar"><button className="ghost editor-back" aria-label="コンテンツ一覧へ戻る" onClick={onBack}>←<span className="mobile-hidden"> コンテンツ</span></button>{statusControl}<div className="deploy-action">{deployButton}</div></header>
    <div className="editor-tools"><span className="publication-label">{doc.common.publication === "draft" ? "下書き" : "公開に設定済み"}</span><button aria-expanded={settings} onClick={() => setSettings(!settings)}>記事設定</button><button disabled={disabled} onClick={onSave}>入力を確認</button>{doc.common.publication === "draft" ? <button disabled={disabled || !canPublish} title={!canPublish ? "公開に必要な項目を入力してください" : ""} onClick={onPublish}>公開に設定</button> : <button disabled={disabled} onClick={onUnpublish}>非公開に設定</button>}{doc.placement.kind === "journal" && journalDefaultsControl}</div>
    <p className="autosave-hint">入力はこのブラウザに自動保存され、保留変更の対象になります。サイトへの反映は別操作です。</p>
    {feedback}
    <fieldset disabled={disabled} className="editor-content-fields"><section className="cms-editor-layout"><article className="editor-document"><input className="title-input" value={doc.common.title} onChange={(event) => updateCommon("title", event.target.value)} placeholder="タイトル" /><textarea aria-label="説明・リード文" className="canvas-lead" rows={2} value={doc.common.description} onChange={(event) => updateCommon("description", event.target.value)} placeholder="説明・リード文" /><small className="summary-hint">一覧・本文冒頭の説明です。Journalで空欄の場合はOG説明を使用します。</small><CanvasFields doc={doc} position="before" update={updatePlacement} pickMedia={(target) => { setMediaTarget(target); setMedia("field"); }} /><VisualEditor editable={!disabled} key={doc.id} documents={documents} value={doc.body} onChange={(body) => { if (body !== doc.body.trim()) onChange({ ...doc, body }); }} onOpenMedia={(insert) => { insertEditorImage.current = insert; setMedia("body"); }} /><CanvasFields doc={doc} position="after" update={updatePlacement} pickMedia={(target) => { setMediaTarget(target); setMedia("field"); }} /><details className="syntax-help"><summary>本文の記法・リンクの埋め込み</summary><p>＋または / でブロックを追加できます。空の段落にURLを貼り付けると、通常リンク・リンクカード・対応サービスの埋め込みを選べます。</p><p>リンクカードではサイト内の記事を選択できます。外部ページのタイトル・説明・画像は自動取得し、手動修正と再取得もできます。YouTube・Xの投稿・SpotifyはURLから埋め込めます。</p><p>既存のiframeはHTML互換ブロックとして保持します。専用ブロックの「編集」からURLや表示方法を変更できます。</p><pre>{'```riddle-embed\n{ "kind": "card", "url": "/journal/2026-08-02/" }\n```'}</pre><p>通常リンクのMarkdown記法: <code>[表示する文字](https://example.com)</code>。埋め込みの種類は <code>card / youtube / x / spotify</code> です。</p></details><label className="canvas-tags">タグ<TagInput key={doc.id} documentId={doc.id} tags={doc.common.tags} onCommit={(tags) => updateCommon("tags", tags)} /></label></article>
      {settings && <aside className="cms-settings"><header><div><p>Settings</p><h2>記事設定</h2></div><button onClick={() => setSettings(false)}>閉じる</button></header><label>配置先<input value={doc.placement.kind} disabled /></label><label>公開状態<select value={doc.common.publication} onChange={(event) => event.target.value === "published" ? onPublish() : onUnpublish()}><option value="draft">下書き</option><option value="published" disabled={disabled || !canPublish}>公開</option></select></label><label>公開日<input type="date" value={doc.common.date} onChange={(event) => onChange(setPublicationDate(doc, event.target.value))} /></label>{doc.common.publication === "draft" && !doc.publicationHistory?.hasBeenPublished && doc.publicationHistory?.dateSource !== "manual" && <p className="publication-date-hint">初回公開時に日本時間の公開日を設定します。日付を入力すると、その日を公開日として使います。</p>}<PlacementSettings doc={doc} update={updatePlacement} pickMedia={(target) => { setMediaTarget(target); setMedia("field"); }} /><section className="publish-checks"><h3>公開チェック</h3>{checks.map((check) => <p className={check.ok ? "ok" : "bad"} key={check.label}>{check.ok ? "✓" : "○"} {check.label}</p>)}</section><button onClick={() => setDeveloper(!developer)}>開発者情報</button>{developer && <div className="developer-info"><code>{doc.file?.path || "未保存"}</code><code>{doc.file?.revision || "revisionなし"}</code><textarea readOnly value={buildContentMarkdown(doc)} /></div>}<button className="danger" onClick={onDelete}>削除する</button></aside>}
    </section></fieldset>
    {media && <div className="modal-backdrop media-picker"><div className="media-picker-panel"><header><h2>メディアを選択</h2><button onClick={() => setMedia(null)}>閉じる</button></header><MediaLibrary registry={registry} onSelect={chooseMedia} /></div></div>}
  </main>;
}

function PlacementSettings({ doc, update, pickMedia }: { doc: ContentDocument; update: (data: ContentDocument["placement"]["data"]) => void; pickMedia: (target: string) => void }) {
  if (doc.placement.kind === "about") return null;
  if (doc.placement.kind === "journal") { const data = doc.placement.data; return <section><h3>Journal設定</h3><label>記事種別<select value={data.articleType} onChange={(event) => update({ ...data, articleType: event.target.value as typeof data.articleType })}><option value="journal">Journal</option><option value="making">Making</option><option value="report">Report</option></select></label><label>slug<input value={data.slug} onChange={(event) => update({ ...data, slug: event.target.value })} /></label><MediaField label="サムネイル" value={data.thumbnail} onChange={(value) => update({ ...data, thumbnail: value })} onPick={() => pickMedia("thumbnail")} /><label>サムネイルalt<input value={data.thumbnailAlt} onChange={(event) => update({ ...data, thumbnailAlt: event.target.value })} /></label><label>OG説明<textarea value={data.ogDescription} onChange={(event) => update({ ...data, ogDescription: event.target.value })} /><small>共有カード向けの説明です。空欄なら説明・リード文を使用します。</small></label><MediaField label="OG画像" value={data.ogImage} onChange={(value) => update({ ...data, ogImage: value })} onPick={() => pickMedia("ogImage")} /></section>; }
  if (doc.placement.kind === "songs") return null;
  if (doc.placement.kind === "gallery") { const data = doc.placement.data; return <section><h3>Gallery設定</h3><label>slug<input value={data.slug} onChange={(event) => update({ ...data, slug: event.target.value })} /></label><label className="check-row"><input type="checkbox" checked={data.detail} onChange={(event) => update({ ...data, detail: event.target.checked })} />詳細ページを作る</label><MediaField label="サムネイル" value={data.thumbnail} onChange={(value) => update({ ...data, thumbnail: value })} onPick={() => pickMedia("thumbnail")} /></section>; }
  const data = doc.placement.data; return <section><h3>Projects設定</h3><label>slug<input value={data.slug} onChange={(event) => update({ ...data, slug: event.target.value })} /></label></section>;
}
function CanvasFields({ doc, position, update, pickMedia }: { doc: ContentDocument; position: "before" | "after"; update: (data: ContentDocument["placement"]["data"]) => void; pickMedia: (target: string) => void }) {
  if (doc.placement.kind === "about") return null;
  if (doc.placement.kind === "journal") return null;
  if (doc.placement.kind === "songs") {
    const data = doc.placement.data;
    const videoId = normalizeYouTubeId(data.youtubeId);
    return position === "before" ? <section className="canvas-fields"><h2>動画</h2><label>YouTube URL または ID<input value={data.youtubeId} onChange={(event) => update({ ...data, youtubeId: event.target.value })} /></label>{videoId && <div className="canvas-video-preview"><iframe src={`https://www.youtube-nocookie.com/embed/${videoId}`} title={`${doc.common.title || "Song"} 動画プレビュー`} loading="lazy" allowFullScreen /></div>}</section> : <section className="canvas-fields"><h2>クレジット</h2><textarea value={data.credits} onChange={(event) => update({ ...data, credits: event.target.value })} /><h2>歌詞</h2><textarea rows={9} value={data.lyrics} onChange={(event) => update({ ...data, lyrics: event.target.value })} /></section>;
  }
  if (doc.placement.kind === "gallery") {
    if (position === "after") return null;
    const data = doc.placement.data;
    return <section className="canvas-fields"><h2>作品画像</h2><MediaField label="メイン画像" value={data.image} onChange={(value) => update({ ...data, image: value })} onPick={() => pickMedia("image")} />{data.image && <img className="canvas-media-preview" src={mediaUrl(data.image, "image")} alt={doc.common.title || "作品画像"} />}</section>;
  }
  const data = doc.placement.data;
  return position === "before" ? <section className="canvas-fields"><h2>プロジェクト</h2><label>状態<select value={data.status} onChange={(event) => update({ ...data, status: event.target.value as ProjectStatus })}><option value="active">進行中</option><option value="paused">休止中</option><option value="completed">完了</option><option value="archived">アーカイブ</option></select></label><MediaField label="ヒーロー画像" value={data.hero} onChange={(value) => update({ ...data, hero: value })} onPick={() => pickMedia("hero")} />{data.hero && <img className="canvas-media-preview" src={mediaUrl(data.hero, "image")} alt={`${doc.common.title || "Project"} ヒーロー画像`} />}</section> : <section className="canvas-fields"><h2>リンク</h2>{data.links.map((link, index) => <div className="project-link-row" key={index}><label>ラベル<input value={link.label} onChange={(event) => update({ ...data, links: data.links.map((item, itemIndex) => itemIndex === index ? { ...item, label: event.target.value } : item) })} /></label><label>URL<input type="url" value={link.url} onChange={(event) => update({ ...data, links: data.links.map((item, itemIndex) => itemIndex === index ? { ...item, url: event.target.value } : item) })} /></label><button type="button" onClick={() => update({ ...data, links: data.links.filter((_, itemIndex) => itemIndex !== index) })}>削除</button></div>)}<button type="button" onClick={() => update({ ...data, links: [...data.links, { label: "", url: "" }] })}>リンクを追加</button></section>;
}
function MediaField({ label, value, onChange, onPick }: { label: string; value: string; onChange: (value: string) => void; onPick: () => void }) { return <label>{label}<span className="input-with-action"><input value={value} onChange={(event) => onChange(event.target.value)} /><button type="button" onClick={onPick}>選択</button></span></label>; }
