import { useRef, useState, type ReactNode } from "react";
import { buildContentMarkdown, normalizeYouTubeId, publicationChecks } from "../lib/cmsMarkdown";
import { mediaUrl } from "../lib/mediaRegistry";
import type { ContentDocument, EditingStatus, ProjectStatus } from "../types/content";
import type { MediaAsset, MediaRegistry } from "../types/media";
import { MediaLibrary } from "./MediaLibrary";
import { type EditorImage, VisualEditor } from "./VisualEditor";

type Props = { document: ContentDocument; status: EditingStatus; notice: string; deployButton: ReactNode; registry: MediaRegistry; conflict: { target: "content" | "media"; operation: "save" | "delete"; documentId?: string; expectedRevision?: string; currentRevision?: string } | null; onChange: (doc: ContentDocument) => void; onSave: () => void; onPublish: () => void; onUnpublish: () => void; onBack: () => void; onReload: () => void; onDiscard: () => void; onForce: () => void; onDelete: () => void };
export function CmsEditor({ document: doc, status, notice, deployButton, registry, conflict, onChange, onSave, onPublish, onUnpublish, onBack, onReload, onDiscard, onForce, onDelete }: Props) {
  const [settings, setSettings] = useState(false); const [media, setMedia] = useState<"body" | "field" | null>(null); const [mediaTarget, setMediaTarget] = useState<string>(""); const [developer, setDeveloper] = useState(false);
  const insertEditorImage = useRef<((image: EditorImage) => void) | null>(null);
  const updateCommon = <K extends keyof ContentDocument["common"]>(key: K, value: ContentDocument["common"][K]) => onChange({ ...doc, common: { ...doc.common, [key]: value } });
  const updatePlacement = (data: ContentDocument["placement"]["data"]) => onChange({ ...doc, placement: { ...doc.placement, data } as ContentDocument["placement"] });
  function chooseMedia(asset: MediaAsset) {
    if (media === "body" && asset.type === "image" && insertEditorImage.current) insertEditorImage.current({ src: mediaUrl(asset.publicId, asset.type), alt: asset.alt || asset.displayName });
    else if (media === "body") { const insertion = asset.type === "video" ? `\n\n<video controls src="${mediaUrl(asset.publicId, asset.type)}"></video>\n\n` : `\n\n<audio controls src="${mediaUrl(asset.publicId, asset.type)}"></audio>\n\n`; onChange({ ...doc, body: `${doc.body.trimEnd()}${insertion}` }); }
    else if (doc.placement.kind === "journal") updatePlacement({ ...doc.placement.data, [mediaTarget]: asset.publicId });
    else if (doc.placement.kind === "gallery") updatePlacement({ ...doc.placement.data, [mediaTarget]: asset.publicId });
    else if (doc.placement.kind === "projects") updatePlacement({ ...doc.placement.data, [mediaTarget]: asset.publicId });
    setMedia(null);
  }
  const checks = publicationChecks(doc); const canPublish = checks.every((check) => check.ok); const statusLabel = { clean: "保存済み", dirty: "ブラウザに保存済み", saving: "保存中", conflict: "競合", error: "保存エラー" }[status];
  return <main className="editor-shell"><header className="editor-topbar"><button className="ghost" onClick={onBack}>← コンテンツ</button><span className={`status-pill status-${status}`} title={notice}>{statusLabel} · 公開設定: {doc.common.publication === "draft" ? "下書き" : "公開"}</span><div className="editor-actions"><button onClick={() => setSettings(!settings)}>記事設定</button>{doc.common.publication === "draft" ? <><button onClick={onSave}>下書きを保存</button><button className="primary" disabled={!canPublish} title={!canPublish ? "公開に必要な項目を入力してください" : ""} onClick={onPublish}>公開する</button></> : <><button className="primary" onClick={onSave}>変更を保存</button><button onClick={onUnpublish}>非公開にする</button></>}</div><div className="deploy-action">{deployButton}</div></header>
    {conflict && <div className="conflict-bar"><div><strong>外部で変更されています</strong><span>{notice}</span></div><div className="button-row"><button onClick={onReload}>GitHub版を再読み込み</button><button onClick={onDiscard}>保留変更を破棄</button><button className="danger" onClick={onForce}>{conflict.operation === "delete" ? "強制削除" : "強制上書き"}</button></div></div>}
    <section className="cms-editor-layout"><article className="editor-document"><input className="title-input" value={doc.common.title} onChange={(event) => updateCommon("title", event.target.value)} placeholder="タイトル" /><textarea className="canvas-lead" rows={2} value={doc.common.description} onChange={(event) => updateCommon("description", event.target.value)} placeholder="説明・リード文" /><CanvasFields doc={doc} position="before" update={updatePlacement} pickMedia={(target) => { setMediaTarget(target); setMedia("field"); }} /><VisualEditor value={doc.body} onChange={(body) => { if (body !== doc.body.trim()) onChange({ ...doc, body }); }} onOpenMedia={(insert) => { insertEditorImage.current = insert; setMedia("body"); }} /><CanvasFields doc={doc} position="after" update={updatePlacement} pickMedia={(target) => { setMediaTarget(target); setMedia("field"); }} /><label className="canvas-tags">タグ<input value={doc.common.tags.join(", ")} onChange={(event) => updateCommon("tags", event.target.value.split(",").map((tag) => tag.trim()).filter(Boolean))} placeholder="タグをカンマで区切る" /></label></article>
      {settings && <aside className="cms-settings"><header><div><p>Settings</p><h2>記事設定</h2></div><button onClick={() => setSettings(false)}>閉じる</button></header><label>配置先<input value={doc.placement.kind} disabled /></label><label>日付<input type="date" value={doc.common.date} onChange={(event) => updateCommon("date", event.target.value)} /></label><PlacementSettings doc={doc} update={updatePlacement} pickMedia={(target) => { setMediaTarget(target); setMedia("field"); }} /><section className="publish-checks"><h3>公開チェック</h3>{checks.map((check) => <p className={check.ok ? "ok" : "bad"} key={check.label}>{check.ok ? "✓" : "○"} {check.label}</p>)}</section><button onClick={() => setDeveloper(!developer)}>開発者情報</button>{developer && <div className="developer-info"><code>{doc.file?.path || "未保存"}</code><code>{doc.file?.revision || "revisionなし"}</code><textarea readOnly value={buildContentMarkdown(doc)} /></div>}<button className="danger" onClick={onDelete}>削除する</button></aside>}
    </section>
    {media && <div className="modal-backdrop media-picker"><div className="media-picker-panel"><header><h2>メディアを選択</h2><button onClick={() => setMedia(null)}>閉じる</button></header><MediaLibrary registry={registry} onSelect={chooseMedia} /></div></div>}
  </main>;
}

function PlacementSettings({ doc, update, pickMedia }: { doc: ContentDocument; update: (data: ContentDocument["placement"]["data"]) => void; pickMedia: (target: string) => void }) {
  if (doc.placement.kind === "journal") { const data = doc.placement.data; return <section><h3>Journal設定</h3><label>記事種別<select value={data.articleType} onChange={(event) => update({ ...data, articleType: event.target.value as typeof data.articleType })}><option value="journal">Journal</option><option value="making">Making</option><option value="report">Report</option></select></label><label>slug<input value={data.slug} onChange={(event) => update({ ...data, slug: event.target.value })} /></label><MediaField label="サムネイル" value={data.thumbnail} onChange={(value) => update({ ...data, thumbnail: value })} onPick={() => pickMedia("thumbnail")} /><label>サムネイルalt<input value={data.thumbnailAlt} onChange={(event) => update({ ...data, thumbnailAlt: event.target.value })} /></label><MediaField label="OG画像" value={data.ogImage} onChange={(value) => update({ ...data, ogImage: value })} onPick={() => pickMedia("ogImage")} /></section>; }
  if (doc.placement.kind === "songs") return null;
  if (doc.placement.kind === "gallery") { const data = doc.placement.data; return <section><h3>Gallery設定</h3><label>slug<input value={data.slug} onChange={(event) => update({ ...data, slug: event.target.value })} /></label><label className="check-row"><input type="checkbox" checked={data.detail} onChange={(event) => update({ ...data, detail: event.target.checked })} />詳細ページを作る</label><MediaField label="サムネイル" value={data.thumbnail} onChange={(value) => update({ ...data, thumbnail: value })} onPick={() => pickMedia("thumbnail")} /></section>; }
  const data = doc.placement.data; return <section><h3>Projects設定</h3><label>slug<input value={data.slug} onChange={(event) => update({ ...data, slug: event.target.value })} /></label></section>;
}
function CanvasFields({ doc, position, update, pickMedia }: { doc: ContentDocument; position: "before" | "after"; update: (data: ContentDocument["placement"]["data"]) => void; pickMedia: (target: string) => void }) {
  if (doc.placement.kind === "journal") return null;
  if (doc.placement.kind === "songs") {
    const data = doc.placement.data;
    const videoId = normalizeYouTubeId(data.youtubeId);
    return position === "before" ? <section className="canvas-fields"><h2>動画</h2><label>YouTube URL または ID<input value={data.youtubeId} onChange={(event) => update({ ...data, youtubeId: event.target.value })} /></label>{videoId && <div className="canvas-video-preview"><iframe src={`https://www.youtube-nocookie.com/embed/${videoId}`} title={`${doc.common.title || "Song"} 動画プレビュー`} loading="lazy" allowFullScreen /></div>}</section> : <section className="canvas-fields"><h2>クレジット</h2><textarea value={data.credits} onChange={(event) => update({ ...data, credits: event.target.value })} /><h2>歌詞</h2><textarea rows={9} value={data.lyrics} onChange={(event) => update({ ...data, lyrics: event.target.value })} /></section>;
  }
  if (doc.placement.kind === "gallery") {
    if (position === "after") return null;
    const data = doc.placement.data;
    return <section className="canvas-fields"><h2>作品画像</h2><MediaField label="メイン画像" value={data.image} onChange={(value) => update({ ...data, image: value })} onPick={() => pickMedia("image")} />{data.image && <img className="canvas-media-preview" src={mediaUrl(data.image, "image")} alt={doc.common.title || "作品画像"} />}</section>;
  }
  const data = doc.placement.data;
  return position === "before" ? <section className="canvas-fields"><h2>プロジェクト</h2><label>状態<select value={data.status} onChange={(event) => update({ ...data, status: event.target.value as ProjectStatus })}><option value="active">進行中</option><option value="paused">休止中</option><option value="completed">完了</option><option value="archived">アーカイブ</option></select></label><MediaField label="ヒーロー画像" value={data.hero} onChange={(value) => update({ ...data, hero: value })} onPick={() => pickMedia("hero")} />{data.hero && <img className="canvas-media-preview" src={mediaUrl(data.hero, "image")} alt={`${doc.common.title || "Project"} ヒーロー画像`} />}</section> : <section className="canvas-fields"><h2>リンク</h2>{data.links.map((link, index) => <div className="project-link-row" key={index}><label>ラベル<input value={link.label} onChange={(event) => update({ ...data, links: data.links.map((item, itemIndex) => itemIndex === index ? { ...item, label: event.target.value } : item) })} /></label><label>URL<input type="url" value={link.url} onChange={(event) => update({ ...data, links: data.links.map((item, itemIndex) => itemIndex === index ? { ...item, url: event.target.value } : item) })} /></label><button type="button" onClick={() => update({ ...data, links: data.links.filter((_, itemIndex) => itemIndex !== index) })}>削除</button></div>)}<button type="button" onClick={() => update({ ...data, links: [...data.links, { label: "", url: "" }] })}>リンクを追加</button></section>;
}
function MediaField({ label, value, onChange, onPick }: { label: string; value: string; onChange: (value: string) => void; onPick: () => void }) { return <label>{label}<span className="input-with-action"><input value={value} onChange={(event) => onChange(event.target.value)} /><button type="button" onClick={onPick}>選択</button></span></label>; }
